# Cloudflare Pages configuration for Telecare Platform
name = "telecare-platform"
compatibility_date = "2024-07-20"
compatibility_flags = ["nodejs_compat"]

# Pages build output directory
pages_build_output_dir = "out"

# Environment variables
[env.production.vars]
ENVIRONMENT = "production"
NODE_ENV = "production"

[env.preview.vars]
ENVIRONMENT = "staging"
NODE_ENV = "development"

# D1 Database bindings
[[env.production.d1_databases]]
binding = "DB"
database_name = "telecare-platform-prod"
database_id = "251c7686-fe80-462d-8244-2e85d9fcaa73"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "telecare-platform-staging"
database_id = ""  # Will be set after creating the database

# R2 Storage bindings (for file uploads)
[[env.production.r2_buckets]]
binding = "STORAGE"
bucket_name = "telecare-platform-storage-prod"

[[env.preview.r2_buckets]]
binding = "STORAGE"
bucket_name = "telecare-platform-storage-staging"

# KV bindings (for caching and session storage)
[[env.production.kv_namespaces]]
binding = "CACHE"
id = "fc83186cc3374443b02c8f7a7876291c"

[[env.preview.kv_namespaces]]
binding = "CACHE"
id = ""  # Will be set after creating the namespace